apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-springboot-jpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee-container
          image: employee-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080